Create a package to save data locally
calyptia/cli pull request #300
Opened 2023-02-02 09:45 UTC by gabrielbussolo

Signed-off-by: Gabriel Bussolo <gabriel@calyptia.com>

# Summary of this proposal

This PR intends to resolve #299 

Creates a package to be used to save small data.

The usability basically is `localData.Save(key, data)`, `localData.Get(key)`, `localData.Delete(key)`, it will try to save on the os keyring if its not available it will save on a local file like we were doing before, the refactor was around the usability and the code duplication, not around the functionality itself so it remains the same, just a bit **more reusable**, **documented** and with **tests**.

If it looks good for everyone it will be used on the #256 implementation also

## Notes for the reviewer

## Issue(s) number(s)

*Disclaimer: Please do not create a Pull Request without creating an issue first.*

## Checklist for submitter

- [ ] My PR has a related issue/bug number.
- [ ] My PR provides tests
  - [ ] Integration tests are added/passes
  - [ ] Unit tests are added/passes
  - [ ] End-to-end tests added/passes
  - [ ] Static code check added/passes
  - [ ] Linting on documentation added/passes
  - [ ] Does not affect code coverage stats
- [ ] My PR requires updating dependencies
- [ ] My PR has the documentation changes required.

## Checklist for reviewer

- [ ] The proposal fixes a bug/issue or implements a new feature that is well described.
- [ ] The proposal has sufficient test cases that covers the changes.
  - [ ] If changes an API, it does not break backwards compatibility (-1 major version).
- [ ] If integration is required, the proposal has integration tests.
- [ ] The proposal does not break coverage stats
- [ ] The proposal has the required documentation changes.

## Backport

- [ ] Backport to the latest stable release.

2023-02-02 09:54 UTC, patrick-stephens commented
Is there no existing standard package to do this @gabrielbussolo ?

2023-02-02 10:00 UTC, gabrielbussolo commented
> Is there no existing standard package to do this @gabrielbussolo ?

either on golang standard library or our packages we dont have a solution like we have been doing here, we have been repeating this code on cli codebase so i basically "generify"  it and externalized to package to be more reusable

2023-02-02 16:53 UTC, patrick-stephens commented
For me it was more is there a standard or good existing package people generally use rather than make our own but I'm not averse to it.

2023-02-02 17:51 UTC, nicolasparada commented
@patrick-stephens https://github.com/99designs/keyring this one is better, securer and has a fallback mechanism to store as plain file. But would break existing flow, that's why we haven't switched to it.

2023-02-02 17:51 UTC, nicolasparada commented on cmd/calyptia/config_url.go
> +const UrlToken = "base_url"
```suggestion
const keyBaseURL = "base_url"
```

2023-02-02 17:51 UTC, nicolasparada commented on cmd/calyptia/config_token.go
> +const TokenKey = "token"
```suggestion
const keyToken = "token"
```

2023-02-02 17:57 UTC, nicolasparada approved these changes
Please rename some of the keys. Prefix all of them with `Key`, ex `KeyFoo`.

Also sort imports and stuff.

```bash
goimports -w -local github.com/calyptia/ .
```

2023-02-02 17:58 UTC, nicolasparada requested changes
Sorry, I meant to request changes.

2023-02-03 15:38 UTC, nicolasparada requested changes
Oh, didn't notice the package name.
There is no need for all that subpackaging.

You can create a folder called `keyring` and but the code there instead of `internal/platform/local-data`.

The new `keyring` package is basically a wrapper over keyring but will local filesystem fallback.

2023-02-06 07:54 UTC, gabrielbussolo commented
> Oh, didn't notice the package name. There is no need for all that subpackaging.
> 
> You can create a folder called `keyring` and but the code there instead of `internal/platform/local-data`.
> 
> The new `keyring` package is basically a wrapper over keyring but will local filesystem fallback.

the reason for that is on the pr description 
> ps: the package is internal to prevent imports on other projects and with it we don't need to provide support, but i put it on > the platform package what means that one day it can be decoupled from the cli to be used by other projects. (according > > with package oriented design)

but to resume basically isn't from the scope of calyptia/cli keep a keyring api for external use, lets keep it on internal.

2023-02-08 14:10 UTC, nicolasparada commented
That is true for almost all packages but we are not using `internal` in any of them.
I wouldn't use unless there is a strong reason, which we don't have.

And platform is just meaningless, it's not idiomatic at all.

`local-data` is also not a way to name a package due to the dash. It can be `localdata` if you don't like simply `keyring`.

2023-02-17 15:12 UTC, patrick-stephens commented on cmd/calyptia/auth.go
> +const backUpFolder = ".calyptia"
Things like this need to be captured in the docs - we need to ensure complete removal for package install for example. Where exactly is this folder (under a home area for a user or in the calyptia area)?

Please if you're adding extra directories or files then make sure you raise an issue on calyptia/core-images so we track the file/directory properly for packages. It's best practice and quite often a requirement for more secure systems.

2023-02-17 15:28 UTC, nicolasparada requested changes
There is no need for a `pkg` directory, it's verbose to have a package called "package". Does not provide anything.

2023-02-20 11:02 UTC, patrick-stephens commented on cmd/calyptia/auth.go
> +const backUpFolder = ".calyptia"
What happens if we run this as a user with no home directory?
Can we make it configurable?

2023-02-20 12:25 UTC, nicolasparada approved these changes

2023-02-20 17:28 UTC, merged