send invitation
calyptia/cli pull request #431
Opened 2023-05-23 18:24 UTC by nicolasparada

Adding the following command:

```bash
calyptia create invitation user@example.org
```

2023-05-23 18:28 UTC, pwhelan submitted a review, later dismissed
LGTM

2023-05-23 19:05 UTC, nicolasparada commented
Waiting on https://github.com/calyptia/cloud-e2e/pull/79

2023-05-24 10:23 UTC, niedbalski approved these changes
LGTM

2023-05-24 10:35 UTC, niedbalski requested changes
Minor nitpicks

2023-05-24 10:35 UTC, niedbalski commented on cmd/invitation/send_invitation.go
> +	fs.StringVar(&redirectURI, "redirect-uri", redirectURI, "Redirect URI for the invitation, leave the default value if you don't know what it is")
Where are you using this value? You should set it to "https://core.calyptia.com" and use redirectURI

2023-05-24 11:22 UTC, merged

2023-05-24 16:16 UTC, nicolasparada commented
@niedbalski I think the change to the redirect url won't pick the correct default value. It will always use the prod ui.