rename aggregator cmd to core_instance
calyptia/cli pull request #61
Opened 2022-06-10 14:17 UTC by nicolasparada

# Summary of this proposal

Renaming these commands:

```txt
calyptia get aggregators =>   calyptia get core_instances
calyptia update aggregator => calyptia update core_instance
```

The old command name remains working as an alias.

## Notes for the reviewer

## Issue(s) number(s)

*Disclaimer: Please do not create a Pull Request without creating an issue first.*

## Checklist for submitter

- [ ] My PR has a related issue/bug number.
- [ ] My PR provides tests
  - [ ] Integration tests are added/passes
  - [ ] Unit tests are added/passes
  - [ ] End-to-end tests added/passes
  - [ ] Static code check added/passes
  - [ ] Linting on documentation added/passes
  - [ ] Does not affect code coverage stats
- [ ] My PR requires updating dependencies
- [ ] My PR has the documentation changes required.

## Checklist for reviewer

- [ ] The proposal fixes a bug/issue or implements a new feature that is well described.
- [ ] The proposal has sufficient test cases that covers the changes.
  - [ ] If changes an API, it does not break backwards compatibility (-1 major version).
- [ ] If integration is required, the proposal has integration tests.
- [ ] The proposal does not break coverage stats
- [ ] The proposal has the required documentation changes.

## Backport

- [ ] Backport to the latest stable release.

2022-06-10 14:26 UTC, nicolasparada commented
Open to rename to just `instance` or even just `core`.

2022-06-12 14:38 UTC, niedbalski requested changes
@nicolasparada 🤔 What is the context for this PR? We are renaming the semantics for "core" as in #60 , under "calyptia core.." prefix.

2022-06-12 15:07 UTC, nicolasparada commented
Even if the product is called "core" the command does need to be called like that necessarily.
"Create core" sounds weird 🤔

2022-06-14 17:47 UTC, niedbalski approved these changes

2022-06-14 17:47 UTC, merged